# -*- coding: utf-8 -*-
"""Trashly.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19oLTozqYd6cTM_ThaoTse2F7N1l8OagM
"""

# Commented out IPython magic to ensure Python compatibility.
import os, shutil
import zipfile
import random
from random import sample
import shutil
from shutil import copyfile
import pathlib
from pathlib import Path
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm as tq

# %matplotlib inline
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.image import imread

import cv2
from PIL import Image
import skimage
from skimage import io
from skimage.transform import resize
from skimage.transform import rotate, AffineTransform, warp
from skimage import img_as_ubyte
from skimage.exposure import adjust_gamma
from skimage.util import random_noise
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize

import keras
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, ConfusionMatrixDisplay
import tensorflow as tf
from tensorflow.keras import Model, layers
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator, img_to_array, load_img
from tensorflow.keras.optimizers import Adam, RMSprop, SGD
from tensorflow.keras.layers import InputLayer, Conv2D, SeparableConv2D, MaxPooling2D, MaxPool2D, Dense, Flatten, Dropout, BatchNormalization, GlobalAveragePooling2D
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.applications import MobileNet
from tensorflow.keras.applications.densenet import DenseNet121
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import ModelCheckpoint, Callback, EarlyStopping, ReduceLROnPlateau
from google.colab import files

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

tf.__version__

!curl -L -o garbage-classification-v2.zip\
  "https://www.kaggle.com/api/v1/datasets/download/sumn2u/garbage-classification-v2"

!unzip garbage-classification-v2.zip

!ls

# Membuat subplot daftar file gambar per kelas sampah
garbage_img = {}
path = "original"

for class_folder in os.listdir(path):
    garbage_img[class_folder] = os.listdir(os.path.join(path, class_folder))

fig, axs = plt.subplots(len(garbage_img), 5, figsize=(15, 15))

for i, class_name in enumerate(garbage_img):
    images = np.random.choice(garbage_img[class_name], 5, replace=False)

    for j, image_name in enumerate(images):
        img_path = os.path.join(path, class_name, image_name)
        img = Image.open(img_path)
        axs[i, j].imshow(img)
        axs[i, j].set(xlabel=class_name, xticks=[], yticks=[])

plt.tight_layout()
plt.show()

# Dataset original untuk analisis distribusi
garbage_path = "original"

file_name = []
labels = []
full_path = []

# Mengambil filename, path lengkap dan label kelas
for path, subdirs, files in os.walk(garbage_path):
    for name in files:
        full_path.append(os.path.join(path, name))
        labels.append(os.path.basename(path))
        file_name.append(name)

distribution_train = pd.DataFrame({"path":full_path,'file_name':file_name,"labels":labels})

# Plot distribusi jumlah gambar per kelas
Label = distribution_train['labels']
plt.figure(figsize = (6,6))
sns.set_style("darkgrid")
plot_data = sns.countplot(Label)

def get_image_resolution(filepath):
    with Image.open(filepath) as img:
        return img.size

dataset_path = "original"

data = []

for root, _, files in os.walk(dataset_path):
    for file in files:
        if file.lower().endswith(('.jpg', '.jpeg', '.png')):
            file_path = os.path.join(root, file)
            label = os.path.basename(os.path.dirname(file_path))  # <-- ini
            data.append({
                'filename': file,
                'filepath': file_path,
                'label': label
            })

dataset_df = pd.DataFrame(data)

# Ekstrak resolusi dan aspect ratio
dataset_df['resolution'] = dataset_df['filepath'].apply(get_image_resolution)
dataset_df[['width', 'height']] = pd.DataFrame(dataset_df['resolution'].tolist(), index=dataset_df.index)

dataset_df['aspect_ratio'] = dataset_df['width'] / dataset_df['height']

dataset_df.head()

dataset_df['resolution'].value_counts()

"""# **Data Splitting**"""

X= dataset_df['filepath']
y= dataset_df['label']

X_temp, X_test, y_temp, y_test = train_test_split(
    X, y, test_size=0.3, random_state=300)

X_train, X_val, y_train, y_val = train_test_split(
    X_temp, y_temp, test_size=0.3, random_state=300)

df_train = pd.DataFrame({'filepath': X_train, 'label': y_train, 'set': 'train'})
df_val   = pd.DataFrame({'filepath': X_val,   'label': y_val,   'set': 'val'})
df_test  = pd.DataFrame({'filepath': X_test,  'label': y_test,  'set': 'test'})

print('train size', len(df_train))
print('test size', len(df_test))
print('val size', len(df_val))

df_all = pd.concat([df_train, df_test, df_val], ignore_index=True)

print('===================================================== \n')
print(df_all.groupby(['set', 'label']).size(), '\n')
print('===================================================== \n')

print(df_all.sample(5))

# Memanggil dataset asli yang berisi keseluruhan data gambar yang sesuai dengan labelnya
datasource_path = "dataset/"
# Membuat variabel Dataset, dimana nanti menampung data yang telah dilakukan pembagian data training dan testing
dataset_path = "Dataset-Final/"

for index, row in tq(df_all.iterrows()):
    # Deteksi filepath
    file_path = row['filepath']
    if os.path.exists(file_path) == False:
            file_path = os.path.join(datasource_path,row['label'],row['image'].split('.')[0])

    # Buat direktori tujuan folder
    if os.path.exists(os.path.join(dataset_path,row['set'],row['label'])) == False:
        os.makedirs(os.path.join(dataset_path,row['set'],row['label']))

    # Tentukan tujuan file
    destination_file_name = file_path.split('/')[-1]
    file_dest = os.path.join(dataset_path,row['set'],row['label'],destination_file_name)

    # Salin file dari sumber ke tujuan
    if os.path.exists(file_dest) == False:
        shutil.copy2(file_path,file_dest)

"""# **Image Data Generator**"""

train_dir = "Dataset-Final/train"
test_dir = "Dataset-Final/test"
val_dir = "Dataset-Final/val"

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=25,
    zoom_range=0.2,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True,
    brightness_range=[0.8, 1.2],
    fill_mode='nearest'
)

val_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)


train_gen = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224,224),
    batch_size=32,
    class_mode='categorical',
    shuffle=True
)

val_gen = val_datagen.flow_from_directory(
    val_dir,
    target_size=(224,224),
    batch_size=32,
    class_mode='categorical',
    shuffle=False
)

test_gen = test_datagen.flow_from_directory(
    test_dir,
    target_size=(224,224),
    batch_size=1,
    class_mode='categorical',
    shuffle=False
)

"""# **Modelling**"""

base_model = MobileNet(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False

model = Sequential([
    base_model,
    GlobalAveragePooling2D(),
    Dropout(0.3),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(train_gen.num_classes, activation='softmax')
])

model.compile(optimizer=Adam(learning_rate=1e-4),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

earlystop = EarlyStopping(patience=5, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(factor=0.2, patience=3)

checkpoint_head = ModelCheckpoint(
    'best_head.keras',
    monitor='val_accuracy',
    mode='max',
    save_best_only=True,
    verbose=1
)

history_head = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=30,
    callbacks=[earlystop, reduce_lr, checkpoint_head]
)

for layer in base_model.layers[-20:]:
    layer.trainable = True

model.compile(
    optimizer=Adam(learning_rate=1e-5),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

checkpoint_finetune = ModelCheckpoint(
    'best_finetuned.keras',
    monitor='val_accuracy',
    mode='max',
    save_best_only=True,
    verbose=1
)

history_finetune = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=10,
    callbacks=[earlystop, reduce_lr, checkpoint_finetune]
)

# Prediksi
Y_pred = model.predict(test_gen)
y_pred = np.argmax(Y_pred, axis=1)
y_true = test_gen.classes
class_labels = list(test_gen.class_indices.keys())

# Classification Report
print("Classification Report:\n")
print(classification_report(y_true, y_pred, target_names=class_labels))

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_labels)
disp.plot(xticks_rotation=45, cmap='Blues')
plt.title("Confusion Matrix")
plt.show()

fig, axs = plt.subplots(1, 2, figsize=(12, 5))

# Plot Akurasi
axs[0].plot(history_finetune.history['accuracy'], label='Training Accuracy')
axs[0].plot(history_finetune.history['val_accuracy'], label='Validation Accuracy')
axs[0].set_title('Fine-tuning Accuracy')
axs[0].legend()

# Plot Loss
axs[1].plot(history_finetune.history['loss'], label='Training Loss')
axs[1].plot(history_finetune.history['val_loss'], label='Validation Loss')
axs[1].set_title('Fine-tuning Loss')
axs[1].legend()

plt.tight_layout()
plt.show()

NUM_CLASSES = len(CLASSES)

# pastikan probabilitas
y_pred = model.predict(test_gen)

# pastikan label
y_true = test_gen.classes

y_true_bin = label_binarize(y_true, classes=range(NUM_CLASSES))

plt.figure(figsize=(10,8))

for i in range(NUM_CLASSES):
    fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_pred[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{CLASSES[i]} (AUC={roc_auc:.2f})")

plt.plot([0,1],[0,1],'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - nah Multiclass")
plt.legend()
plt.grid()
plt.show()